from rest_framework import serializers
from .models import ContactMe

class ContactSerializer(serializers.ModelSerializer):
    class Meta:
        model = Contact
        # id field is autogenerated by django. naes must match models in models.py
        fields = ["name", "email", "number", "message"]